[package]
name = "zp1-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
