[package]
name = "zp1-delegation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zp1-primitives = { workspace = true }
zp1-air = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
